### ISSUE TITLE
Is it compatible with ghost v2?

### ISSUE THREAD

**Issue by gustawdaniel** [ifvictr/ghost-storage-github#11]

**Comment by ifvictr** [comment]
Hey, @gustawdaniel! Sorry for the really late response. I haven't used Ghost in a _very_ long time, so I do not know if it still works or not. However, I'm planning to start using it again, so I'll definitely check if it's still compatible or not. I'll keep you updated! :smiley:

**Comment by ifvictr** [comment]
Hey, @gustawdaniel! Really sorry for the late response. I haven't used Ghost in a _very_ long time, so I don't know if it still works or not. However, I'm planning to start using it again, so I'll definitely check if it's still compatible. I'll keep you updated! :smiley:

**Comment by gustawdaniel** [comment]
Thank you very much @ifvictr.

**Comment by ifvictr** [comment]
@gustawdaniel I've had some time recently to test it out on v2, and I'm happy to say that it still works. However, a few bugs have popped up since (has to do with GitHub's API updating). I'll try to get them patched up soon 😄

**Comment by Artenes** [comment]
Was trying to use your library in the latest version of Ghost without success. This error shows up:

````bash
Invalid authentication type, must be 'basic', 'integration', 'oauth', 'client' or 'netrc
````
probably happens because of some changes in the github api as you have mentioned.

Waiting for the release of the next patch :)

**Comment by ifvictr** [comment]
Hi @Artenes,

I should've made this clear, but the README you're seeing is for the next version, which I haven't released yet. Here's the README for the current release: https://github.com/ifvictr/ghost-github/tree/13ae27ab54b090e9024d39625eb638b5a547d246#ghost-github
