### ISSUE TITLE
Hi ifvictr, just follow the README is enough to install on ghost(v3.2.0) ?

### ISSUE THREAD

**Issue by BetterLuke** [ifvictr/ghost-storage-github#32]
First of all, pretty thanks for your share. 
My question: My ghost version is v3.2.0. I just follow the README, but i can't install it correct. So something should  be update? Honestly, I am a newbie in programming. Please give me more details for how to install this plugin for ghost~ :D  Thanks~

**Comment by ifvictr** [comment]
@BetterLuke Sorry, just saw this. Can you share more details about how you tried to install it? Any errors?

**Comment by ifvictr** [comment]
@BetterLuke I haven't released a new version yet, so anything you see in the README in master won't work for 1.0.2. Refer to this one instead: https://github.com/ifvictr/ghost-storage-github/blob/1.0.2/README.md
