### ISSUE TITLE
it did not work with  Ghost V3.2

### ISSUE THREAD

**Issue by ghost** [ifvictr/ghost-storage-github#33]
Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v10.17.0
    Ghost-CLI Version: 1.12.0
    Environment: production
    Command: 'ghost restart'
Message: We detected a misuse. Please read the stack trace.
Suggestion: journalctl -u ghost_inote-xyz -n 50
Stack: Error: We detected a misuse. Please read the stack trace.
    at Server.server.close (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ifvictr** [comment]
@xiyizhou Hi, is there anything else to this error? I can't tell how ghost-storage-github is related to the issue.

**Comment by ifvictr** [comment]
Ok, I think I was able to reproduce this. Make sure the adapter is in `<your ghost directory>/content/adapters/storage`, not `<your ghost directory>/current/content/adapters/storage`.
